name: Deploy Site to Github Pages
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the site from the repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Build site
        run: |
          # Run Flask-frozen to build the site
          # This puts a `build` directory next to the `static` and `template` folders
          python3 main.py build

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './app/build'

      - name: Upload to Github pages
        id: deployment
        uses: actions/deploy-pages@v2
